title: "Sonic Playground Guides"
description: "Minimal, readable GitHub Pages site for operating guides and manuals."
baseurl: ""
url: ""     
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
highlighter: rouge