title: "Sonic Playground Guides"
description: "Minimal, readable GitHub Pages site for operating guides and manuals."
baseurl: "/sonic-playground-guides"   # <-- This is CRITICAL!
url: "https://buryhoganllc.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
highlighter: rouge

# Optional: Document your main stylesheet
sass:
  style: compressed

# Optional: List custom assets for maintainers
assets:
  - assets/css/main.css
