title: "Sonic Playground Operating Guides"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
